import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import AuthProvider from "@/context/authProvider";
import { Toaster } from "@/components/ui/sonner";

const inter = Josefin_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
